from pathlib import Path

from computer.index import computer


HOME = Path.home()

SPECIAL_FOLDERS = {
    "desktop": HOME / "Desktop",
        "documents": HOME / "Documents",
            "downloads": HOME / "Downloads",
                "pictures": HOME / "Pictures",
                    "videos": HOME / "Videos",
                        "music": HOME / "Music"
                        }


                        def score(kind, path):

                            p = path.lower()

                                score = 0

                                    # Потребителски папки имат най-висок приоритет
                                        if str(HOME).lower() in p:
                                                score += 1000

                                                    priorities = {
                                                            "desktop": 900,
                                                                    "documents": 800,
                                                                            "downloads": 700,
                                                                                    "pictures": 600,
                                                                                            "videos": 500,
                                                                                                    "music": 400,
                                                                                                        }

                                                                                                            for name, value in priorities.items():

                                                                                                                    if name in p:
                                                                                                                                score += value

                                                                                                                                    # Истинските приложения имат по-висок приоритет
                                                                                                                                        if kind == "app":

                                                                                                                                                if p.endswith(".exe"):
                                                                                                                                                            score += 5000

                                                                                                                                                                    elif p.endswith(".lnk"):
                                                                                                                                                                                score += 2500

                                                                                                                                                                                        else:
                                                                                                                                                                                                    score += 1000

                                                                                                                                                                                                        # Предпочитай Program Files
                                                                                                                                                                                                            if "program files" in p:
                                                                                                                                                                                                                    score += 800

                                                                                                                                                                                                                        return score


                                                                                                                                                                                                                        def search(target):

                                                                                                                                                                                                                            target = target.lower().strip()

                                                                                                                                                                                                                                # ---------- Специални папки ----------

                                                                                                                                                                                                                                    if target in SPECIAL_FOLDERS:

                                                                                                                                                                                                                                            folder = SPECIAL_FOLDERS[target]

                                                                                                                                                                                                                                                    if folder.exists():

                                                                                                                                                                                                                                                                return (
                                                                                                                                                                                                                                                                                "folder",
                                                                                                                                                                                                                                                                                                str(folder)
                                                                                                                                                                                                                                                                                                            )

                                                                                                                                                                                                                                                                                                                results = []

                                                                                                                                                                                                                                                                                                                    # ---------- Applications ----------

                                                                                                                                                                                                                                                                                                                        for name, path in computer.apps.items():

                                                                                                                                                                                                                                                                                                                                if name == target:

                                                                                                                                                                                                                                                                                                                                            results.append((
                                                                                                                                                                                                                                                                                                                                                            "app",
                                                                                                                                                                                                                                                                                                                                                                            path,
                                                                                                                                                                                                                                                                                                                                                                                            100000 + score("app", path)
                                                                                                                                                                                                                                                                                                                                                                                                        ))

                                                                                                                                                                                                                                                                                                                                                                                                                elif target in name:

                                                                                                                                                                                                                                                                                                                                                                                                                            results.append((
                                                                                                                                                                                                                                                                                                                                                                                                                                            "app",
                                                                                                                                                                                                                                                                                                                                                                                                                                                            path,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            50000 + score("app", path)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ))

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # ---------- Files ----------

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                for name, path in computer.files.items():

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if name == target:

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    results.append((
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "file",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    path,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    30000 + score("file", path)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ))

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        elif target in name:

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    results.append((
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "file",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    path,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    score("file", path)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ))

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # ---------- Folders ----------

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        for name, path in computer.folders.items():

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if name == target:

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            results.append((
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "folder",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            path,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            10000 + score("folder", path)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ))

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                elif target in name:

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            results.append((
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "folder",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            path,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            score("folder", path)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ))

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if not results:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return None

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        results.sort(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                key=lambda item: item[2],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        reverse=True
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                kind, path, _ = results[0]

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            kind,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    path
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )